application: app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /images
  static_dir: static/images

- url: /.*
  script: main.app
